GITEA_IMAGE: gitea/gitea
APP_NAME: "Gitea: Git with a cup of tea"
RUN_MODE: prod
SSH_PORT: 22
USER_UID: 1002
USER_GID: 1002

DB_TYPE: postgres
DB_NAME: gitea
DB_USER: gitea
DB_PASSWD: gitea
DB_IMAGE: postgres:10-alpine
